function run0001 = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  RUN0001 = IMPORTFILE(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the numeric
%  data.
%
%  RUN0001 = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  RUN0001 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  run0001 = importfile("/Users/trevorlong/Dropbox (MIT)/Wind Tunnel Testing/Testing_Summer2019/run_0001.xlsx", "sheet1", [2, 516]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 31-Jul-2019 15:17:04

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
%if nargin <= 2
%    dataLines = [2, 1000];
%end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 12);

% Specify sheet and range
opts.Sheet = sheetName;
%opts.DataRange = "A" + dataLines(1, 1) + ":L" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Untitled", "Untitled1", "Untitled2", "Untitled3", "Untitled4", "Untitled5", "Untitled6", "Untitled7", "Untitled8", "Untitled9", "Untitled10", "Untitled11"];
opts.SelectedVariableNames = ["Untitled", "Untitled1", "Untitled2", "Untitled3", "Untitled4", "Untitled5", "Untitled6", "Untitled7", "Untitled8", "Untitled9", "Untitled10", "Untitled11"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
run0001 = readtable(workbookFile, opts, "UseExcel", false);
% 
% for idx = 2:size(dataLines, 1)
%     %opts.DataRange = "A" + dataLines(idx, 1) + ":L" + dataLines(idx, 2);
%     tb = readtable(workbookFile, opts, "UseExcel", false);
%     run0001 = [run0001; tb]; %#ok<AGROW>
% end

%% Convert to output type
run0001 = table2array(run0001);
end