function tare = taremat(tarenum, sheetName, dataLines)
%IMPORTFILE1 Convert tare files to .mat tare vectors


workbookFile = sprintf('tare_%04d.xlsx',tarenum);
%  TAREXXXX = IMPORTFILE1(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  TAREXXX = IMPORTFILE1(FILE, SHEET) reads from the specified
%  worksheet.
%
%  TARE0016 = IMPORTFILE1(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  tare0016 = importfile1("/Users/trevorlong/Dropbox (MIT)/Wind Tunnel Testing/Testing_Summer2019/tare_0016.xlsx", "sheet1", [2, 158]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Sep-2019 10:52:22

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 158];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "B" + dataLines(1, 1) + ":D" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Untitled1", "Untitled2", "Untitled3"];
opts.SelectedVariableNames = ["Untitled1", "Untitled2", "Untitled3"];
opts.VariableTypes = ["double", "double", "double"];

% Import the data
tare = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "B" + dataLines(idx, 1) + ":D" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    tare = [tare; tb]; %#ok<AGROW>

end
    tare = nanmean(table2array(tare));
    matfile = sprintf('tare_%04d',tarenum);
    save(matfile,'tare');
    
end